using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("nRadio")]
[assembly: AssemblyCompanyAttribute("Maca134")]
[assembly: AssemblyProductAttribute("nRadio")]
[assembly: AssemblyCopyrightAttribute("Copyright 2015")]
[assembly: AssemblyVersionAttribute("0.0.0.4")]
[assembly: AssemblyFileVersionAttribute("0.0.0.4")]

